from mypy_extensions import NoReturn
from typing import Callable


class Flask:
    def __init__(self, name: str) -> None: ...
    def route(self, route: str) -> Callable: ...
    def run(self, debug: bool=False) -> NoReturn: ...
